---
- name: Register DC-2 Qpids with Management Server
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['qs']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/apigee-opdk-custom-properties/custom-properties.yml
  roles:
  - { role: apigee-opdk-server-self, server_types: ['qs'] }
  - { role: apigee-opdk-setup-qpid-add, tags: ['registration'] }
  - { role: apigee-opdk-setup-status, tags: ['status'] }