---
- name: Update planet cache
  tags: ['cache']
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: edge

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  tags: ['os']
  vars:
    target_hosts: edge

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: edge

- name: Install and configure Openldap pre-requisites
  import_playbook: apigee-os-pre-requisites-epel.yml
  tags: ['os', 'os-epel']
  vars:
    target_hosts: edge

- name: Install and configure Openldap pre-requisites
  import_playbook: apigee-os-pre-requisites-openldap.yml
  tags: ['os', 'os-openldap']
  vars:
    target_hosts: ms

- name: Install and configure Pip pre-requisites
  import_playbook: apigee-os-pre-requisites-pip.yml
  tags: ['os', 'os-pip']
  vars:
    target_hosts: edge

- name: Install and configure Postgres pre-requisites
  import_playbook: apigee-os-pre-requisites-postgres.yml
  tags: ['os', 'os-postgres']
  vars:
    target_hosts: edge

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: edge

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: edge

- name: Install and configure Apigee Edge AIO
  hosts: planet
  gather_facts: no
  tags: ['aio']
  serial: 1
  vars:
    yum_manual_os_packages:
    - openldap-servers
  roles:
  - { role: apigee-opdk-setup-component, profile: 'aio', tags: ['aio']}

- name: Setup org
  include: install-edge-setup-org.yml
  tags: ['org']

- name: Validate RMP
  include: install-edge-rmp-validate.yml
  tags: ['validate-rmp']

- name: Download logs and configs
  tags: ['logs']
  include: apigee-log-config-files.yml
  vars:
    target_hosts: planet





