---
# Commented out in favor of testing if it would work better do this at each component.
#- name: Apigee components should be running
#  hosts: edge
#  become: true
#  become_user: "{{ opdk_user_name }}"
#  strategy: free
#  gather_facts: no
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role: apigee-opdk-start-components, tags: ['start'] }

#- name: Validate self MS
#  hosts: ms
#  become: true
#  become_user: "{{ opdk_user_name }}"
#  strategy: free
#  gather_facts: no
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role: apigee-opdk-server-self, server_types: ['ms'], tags: ['self'] }

#- name: Validate self RMP
#  hosts: rmp
#  become: true
#  become_user: "{{ opdk_user_name }}"
#  strategy: free
#  gather_facts: no
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role: apigee-opdk-server-self, server_types: ['router', 'mp'], tags: ['self']  }

#- name: Validate self QS
#  hosts: qpid
#  become: true
#  become_user: "{{ opdk_user_name }}"
#  strategy: free
#  gather_facts: no
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role: apigee-opdk-server-self, server_types: ['qs'], tags: ['self']  }

#- name: Validate self PS
#  hosts: pg
#  become: true
#  become_user: "{{ opdk_user_name }}"
#  strategy: free
#  gather_facts: no
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }

- name: Upgrade Cassandra
  hosts: ds
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  tags: ['ds']
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  vars:
    upgrade_component: cs,zk
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ds-start'], component_name: 'apigee-cassandra', }
  - { role: apigee-opdk-start-components, tags: ['ds-start'], component_name: 'apigee-zookeeper' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component, component: '{{ upgrade_component }}', tags: ['ds-upgrade'] }

- name: Upgrade Qpid
  hosts: qpid
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  tags: ['qpid']
  vars:
    server_type_names: ['qs']
    upgrade_component: qpid
    block_port: '{{ qpid_messaging_port }}'
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'apigee-qpidd' }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-qpid-server' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ block_port }}' }
  - { role: apigee-opdk-update-component,  component: '{{ upgrade_component }}', tags: ['qpid-upgrade'] }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }

- name: Upgrade Ldap
  hosts: ldap
  become: true
  become_user: "{{ opdk_user_name }}"
  tags: ['ldap']
  serial: 1
  gather_facts: no
  vars:
    hosts: ldap
    upgrade_component: ldap
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ldap-start'], component_name: 'apigee-openldap' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component, component: '{{ upgrade_component }}', tags: ['ldap-upgrade'] }

- name: Upgrade Qpid Edge Components
  hosts: qpid
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['qpid-edge']
  vars:
    upgrade_component: edge
    block_port: '{{ qpid_messaging_port }}'
    server_type_names: ['qs']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'apigee-qpidd' }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-qpid-server' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ block_port }}' }
  - { role: apigee-opdk-update-component, component: '{{ upgrade_component }}', tags: ['qpid-edge-upgrade'] }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }

- name: Upgrade Management Server Edge Components
  hosts: ms
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['ms-edge']
  vars:
    upgrade_component: edge
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ms-edge-start'], component_name: 'edge-management-server' }
  - { role: apigee-opdk-start-components, tags: ['ms-edge-start'], component_name: 'edge-ui-server' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: '{{ upgrade_component }}', tags: ['ms-edge-upgrade'] }

- name: Upgrade Router & Message Processor
  hosts: rmp
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['rmp']
  vars:
    server_type_names: ['router', 'mp']
    upgrade_component: edge
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-router' }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-message-processor' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: '{{ server_type_names }}' }
  - { role: apigee-opdk-update-component,  component: '{{ upgrade_component }}', tags: ['rmp-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: '{{ server_type_names }}' }

- name: Upgrade UI
  hosts: ui
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['ui']
  vars:
    upgrade_component: ui
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ui-start'] }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: '{{ upgrade_component }}', tags: ['ui-upgrade'] }

- name: Upgrade PG in dc-1
  include: upgrade-edge-postgres.yml
  tags: ['pg']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgstandby
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgstandby
  tags: ['logs']
